# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' DAPS main function in Rcpp
#'
#' @param X Genotype matrix (n x p)
#' @param y Phenotype vector (n x 1)
#' @param n Sample size (scalar)
#' @param prior Prior inclusion probabilities (p x 1)
#' @param proposal Proposal matrix (p x L) from SuSiE
#' @param proposal_thresh Proposal threshold (scalar)
#' @param grid Grid of scaled prior variance values (k x 1)
#' @param twas_weight Logical indicating whether to use TWAS weights
#' @param min_abs_corr Minimum absolute correlation for TWAS weights (scalar)
#' @return A list containing models and input data
#'
#' @export
daps_main <- function(X, y, n, prior, proposal, proposal_thresh, grid, twas_weight, min_abs_corr) {
    .Call(`_DAPS_daps_main`, X, y, n, prior, proposal, proposal_thresh, grid, twas_weight, min_abs_corr)
}

#' DAPS_SS main function in Rcpp
#'
#' @param XtX Cross-product of genotype matrix (p x p)
#' @param Xty Cross-product of genotype and phenotype vector (p x 1)
#' @param yty Cross-product of phenotype vector (scalar)
#' @param n Sample size (scalar)
#' @param prior Prior inclusion probabilities (p x 1)
#' @param proposal Proposal matrix (p x L) from SuSiE
#' @param proposal_thresh Proposal threshold (scalar)
#' @param grid Grid of scaled prior variance values (k x 1)
#' @param twas_weight Logical indicating whether to use TWAS weights
#' @param min_abs_corr Minimum absolute correlation for TWAS weights (scalar)
#' @return A list containing models and input data
#'
#' @export
daps_ss_main <- function(XtX, Xty, yty, n, prior, proposal, proposal_thresh, grid, twas_weight, min_abs_corr) {
    .Call(`_DAPS_daps_ss_main`, XtX, Xty, yty, n, prior, proposal, proposal_thresh, grid, twas_weight, min_abs_corr)
}

